// Package storage defines fj-bellows' durable state and accounting boundary.
//
// Live cloud resources remain authoritative for existence. Storage records the
// daemon's mutation intent, recovery metadata, job history, and immutable price
// observations so a restart can reconcile safely and historical statistics do
// not depend on the in-memory event stream.
package storage

import (
	"context"
	"errors"
	"time"
)

// ErrNewerSchema is returned when a database was written by a newer version of
// fj-bellows. Downgrading in place is intentionally unsupported.
var ErrNewerSchema = errors.New("storage schema is newer than this binary")

// ErrNotFound is returned when a requested durable record does not exist.
var ErrNotFound = errors.New("storage record not found")

// Store is the durable persistence contract used by orchestrators and the
// control plane. Implementations must be safe for concurrent use.
type Store interface {
	Close() error
	Health(ctx context.Context) Health

	BeginMutation(ctx context.Context, mutation Mutation) error
	FinishMutation(ctx context.Context, operationID string, state MutationState, externalID, detail string, at time.Time) error
	PendingMutations(ctx context.Context) ([]Mutation, error)

	BeginResource(ctx context.Context, resource Resource) (Resource, error)
	ActivateResource(ctx context.Context, id int64, externalID, name string, providerCreatedAt, at time.Time) error
	SetResourceState(ctx context.Context, id int64, state ResourceState, at time.Time) error
	CloseResource(ctx context.Context, id int64, state ResourceState, reason string, at time.Time) error
	OpenResources(ctx context.Context) ([]Resource, error)

	BeginGeneration(ctx context.Context, generation Generation) (Generation, error)
	SetGenerationState(ctx context.Context, id int64, state GenerationState, at time.Time) error
	OpenGenerations(ctx context.Context) ([]Generation, error)

	StartPhase(ctx context.Context, phase Phase) (Phase, error)
	FinishPhase(ctx context.Context, id int64, outcome, detail string, at time.Time) error
	OpenPhases(ctx context.Context) ([]Phase, error)

	UpsertJob(ctx context.Context, job Job) (Job, error)
	OpenJobs(ctx context.Context) ([]Job, error)
	JobHistory(ctx context.Context, filter HistoryFilter) (JobPage, error)

	BeginSnapshot(ctx context.Context, snapshot Snapshot) (Snapshot, error)
	ActivateSnapshot(ctx context.Context, id int64, externalID string, sizeBytes int64, at time.Time) error
	SetSnapshotState(ctx context.Context, id int64, state SnapshotState, detail string, at time.Time) error
	Snapshots(ctx context.Context, filter SnapshotFilter) ([]Snapshot, error)

	RecordPriceQuote(ctx context.Context, quote PriceQuote) (PriceQuote, error)
	GetPriceQuote(ctx context.Context, id int64) (PriceQuote, error)
	LatestPriceQuote(ctx context.Context, provider, instanceType string) (PriceQuote, error)
	RecordCost(ctx context.Context, entry CostEntry) (CostEntry, error)
	Statistics(ctx context.Context, filter StatisticsFilter) (Statistics, error)
	Retain(ctx context.Context, completedBefore time.Time) (RetentionResult, error)
}

// ResourceGenerationActivator is an optional stronger persistence primitive
// used when a Store can atomically publish a provider allocation together
// with its first filesystem generation. Orchestrators fall back to the two
// Store calls for compatible implementations, but production SQLite uses this
// boundary so no crash can expose an active resource with no cleanliness
// record.
type ResourceGenerationActivator interface {
	ActivateResourceWithGeneration(
		ctx context.Context,
		resourceID int64,
		externalID, name string,
		providerCreatedAt, at time.Time,
		generation Generation,
	) (Generation, error)
}

// Health describes the current database connection and the most recent
// durable write. LastError is process-local and is cleared by the next
// successful write.
type Health struct {
	Healthy             bool
	LastSuccessfulWrite time.Time
	LastError           string
}

// MutationState is the state of an external side-effect intent.
type MutationState string

// Mutation lifecycle states.
const (
	MutationPending   MutationState = "pending"
	MutationSucceeded MutationState = "succeeded"
	MutationFailed    MutationState = "failed"
)

// Mutation records intent before an external provider call. OperationID must
// be generated by the caller and is also suitable for an ownership label.
type Mutation struct {
	OperationID string
	Kind        string
	Provider    string
	Tier        string
	ResourceID  int64
	SnapshotID  int64
	State       MutationState
	ExternalID  string
	Detail      string
	CreatedAt   time.Time
	CompletedAt time.Time
}

// ResourceState describes a provider allocation's durable lifecycle.
type ResourceState string

// Resource lifecycle states.
const (
	ResourceProvisioning ResourceState = "provisioning"
	ResourceActive       ResourceState = "active"
	ResourceResetting    ResourceState = "resetting"
	ResourceDestroying   ResourceState = "destroying"
	ResourceClosed       ResourceState = "closed"
	ResourceFailed       ResourceState = "failed"
	ResourceVanished     ResourceState = "vanished"
)

// Resource is one provider allocation. ProviderCreatedAt remains unchanged
// across rebuilds and is the billing-boundary anchor.
type Resource struct {
	ID                int64
	OperationID       string
	Provider          string
	Driver            string
	Tier              string
	ExternalID        string
	Name              string
	InstanceType      string
	Tag               string
	State             ResourceState
	PriceQuoteID      int64
	ProviderCreatedAt time.Time
	OpenedAt          time.Time
	UpdatedAt         time.Time
	ClosedAt          time.Time
	CloseReason       string
}

// GenerationState describes one clean filesystem generation of a resource.
type GenerationState string

// Generation lifecycle states.
const (
	GenerationPreparing GenerationState = "preparing"
	GenerationReady     GenerationState = "ready"
	GenerationInUse     GenerationState = "in_use"
	GenerationDirty     GenerationState = "dirty"
	GenerationClosed    GenerationState = "closed"
	GenerationFailed    GenerationState = "failed"
)

// Generation distinguishes jobs run before and after an in-place reset.
type Generation struct {
	ID          int64
	ResourceID  int64
	Number      int64
	OperationID string
	ImageID     string
	Fingerprint string
	State       GenerationState
	StartedAt   time.Time
	ReadyAt     time.Time
	ClosedAt    time.Time
}

// PhaseKind is a resource or job lifecycle interval.
type PhaseKind string

// Recorded lifecycle phase kinds.
const (
	PhaseProvisioning PhaseKind = "provisioning"
	PhaseReadyIdle    PhaseKind = "ready_idle"
	PhaseJob          PhaseKind = "job"
	PhaseReset        PhaseKind = "reset"
	PhaseRemoving     PhaseKind = "removing"
	PhaseImageBuild   PhaseKind = "image_build"
)

// Phase stores exact lifecycle intervals. An EndedAt of zero means recovery
// must consider the interval open.
type Phase struct {
	ID           int64
	ResourceID   int64
	GenerationID int64
	JobID        int64
	Kind         PhaseKind
	StartedAt    time.Time
	EndedAt      time.Time
	Outcome      string
	Detail       string
}

// IdentityQuality reports whether workflow identity came from Forgejo's
// canonical workflow metadata or the job-name fallback.
type IdentityQuality string

// Workflow identity quality levels.
const (
	IdentityUnknown  IdentityQuality = "unknown"
	IdentityExact    IdentityQuality = "exact"
	IdentityFallback IdentityQuality = "fallback"
)

// JobStatus is a durable job lifecycle/outcome classification.
type JobStatus string

// Job lifecycle and terminal outcome states.
const (
	JobObserved    JobStatus = "observed"
	JobAssigned    JobStatus = "assigned"
	JobRunning     JobStatus = "running"
	JobSucceeded   JobStatus = "succeeded"
	JobFailed      JobStatus = "failed"
	JobCancelled   JobStatus = "cancelled"
	JobSkipped     JobStatus = "skipped"
	JobInfraFailed JobStatus = "infra_failed"
	JobInterrupted JobStatus = "interrupted"
)

// JobKey uniquely identifies one Forgejo queue handle. Retries can share a
// ForgejoJobID but always have distinct handles.
type JobKey struct {
	Source string
	Handle string
}

// Job is a merged durable view of an observed Forgejo job. UpsertJob treats
// zero-valued optional fields as unknown and never erases known values.
type Job struct {
	ID                     int64
	Source                 string
	Handle                 string
	ForgejoJobID           int64
	Attempt                int64
	RepositoryID           int64
	RepositoryOwnerID      int64
	Repository             string
	Workflow               string
	WorkflowFile           string
	JobName                string
	IdentityQuality        IdentityQuality
	Tier                   string
	Provider               string
	Driver                 string
	ResourceID             int64
	GenerationID           int64
	Status                 JobStatus
	Conclusion             string
	InfrastructureFailure  string
	QueueMeasurementSource string
	RunMeasurementSource   string
	FirstSeenAt            time.Time
	QueuedAt               time.Time
	DispatchedAt           time.Time
	RunnerStartedAt        time.Time
	RunnerFinishedAt       time.Time
	CompletedAt            time.Time
	UpdatedAt              time.Time
}

// SnapshotState is the lifecycle of a daemon-managed golden image.
type SnapshotState string

// Managed snapshot lifecycle states.
const (
	SnapshotBuilding SnapshotState = "building"
	SnapshotActive   SnapshotState = "active"
	SnapshotStale    SnapshotState = "stale"
	SnapshotDeleting SnapshotState = "deleting"
	SnapshotDeleted  SnapshotState = "deleted"
	SnapshotFailed   SnapshotState = "failed"
)

// Snapshot is a provider image owned by one tier and bootstrap fingerprint.
type Snapshot struct {
	ID               int64
	OperationID      string
	Provider         string
	Driver           string
	Tier             string
	ExternalID       string
	Name             string
	Fingerprint      string
	SourceResourceID int64
	State            SnapshotState
	SizeBytes        int64
	CreatedAt        time.Time
	UpdatedAt        time.Time
	CompletedAt      time.Time
	Detail           string
}

// SnapshotFilter selects managed images for reconciliation or inspection.
type SnapshotFilter struct {
	Provider    string
	Tier        string
	Fingerprint string
	States      []SnapshotState
}

// PriceQuote is an immutable provider catalog observation. All monetary rates
// are integer nanounits (10^-9) of Currency.
type PriceQuote struct {
	ID                   int64
	Provider             string
	Driver               string
	InstanceType         string
	Currency             string
	PerHourNanos         int64
	PerMonthNanos        int64
	SnapshotGBMonthNanos int64
	MinimumChargeNanos   int64
	BillingQuantum       time.Duration
	MinimumDuration      time.Duration
	Source               string
	ObservedAt           time.Time
}

// CostKind classifies estimated costs without conflating direct job compute
// with fleet overhead.
type CostKind string

// Cost accounting categories.
const (
	CostDirectCompute   CostKind = "direct_compute"
	CostBilledCompute   CostKind = "billed_compute"
	CostBoot            CostKind = "boot"
	CostWarmIdle        CostKind = "warm_idle"
	CostReset           CostKind = "reset"
	CostBillingOverhead CostKind = "billing_overhead"
	CostImageBuilder    CostKind = "image_builder"
	CostSnapshotStorage CostKind = "snapshot_storage"
)

// CostEntry is an immutable estimate over an interval. Known=false records
// incomplete pricing coverage; it is never interpreted as a zero cost.
type CostEntry struct {
	ID           int64
	ResourceID   int64
	SnapshotID   int64
	JobID        int64
	PriceQuoteID int64
	Kind         CostKind
	Currency     string
	Nanos        int64
	Known        bool
	Estimated    bool
	StartedAt    time.Time
	EndedAt      time.Time
	RecordedAt   time.Time
}

// HistoryFilter selects job history. From is inclusive and To is exclusive.
// Cursor is an opaque value returned by an earlier JobHistory call.
type HistoryFilter struct {
	From       time.Time
	To         time.Time
	Tier       string
	Provider   string
	Repository string
	Workflow   string
	Status     JobStatus
	Limit      int
	Cursor     string
}

// JobPage is a stable, newest-first page ordered by immutable first-seen time
// and database ID.
type JobPage struct {
	Jobs       []Job
	NextCursor string
}

// StatisticsGroupBy controls aggregation of job statistics.
type StatisticsGroupBy string

// Supported statistics aggregation dimensions.
const (
	GroupNone     StatisticsGroupBy = "none"
	GroupWorkflow StatisticsGroupBy = "workflow"
	GroupTier     StatisticsGroupBy = "tier"
	GroupProvider StatisticsGroupBy = "provider"
	GroupDay      StatisticsGroupBy = "day"
)

// StatisticsFilter selects completed and in-flight jobs by immutable first-seen
// time. From is inclusive and To is exclusive. Fleet cost and phase intervals
// are selected by overlap, clipped to this window, and split by UTC day.
type StatisticsFilter struct {
	From       time.Time
	To         time.Time
	Tier       string
	Provider   string
	Repository string
	Workflow   string
	Route      string
	GroupBy    StatisticsGroupBy
}

// StatisticsKey identifies one requested aggregation group. Day is UTC.
type StatisticsKey struct {
	Source       string
	RepositoryID int64
	Repository   string
	Workflow     string
	Tier         string
	Provider     string
	Day          string
}

// DurationSummary contains exact nearest-rank percentiles.
type DurationSummary struct {
	Count int64
	Total time.Duration
	Min   time.Duration
	Max   time.Duration
	P50   time.Duration
	P95   time.Duration
}

// CostTotal keeps currencies separate and exposes incomplete coverage.
type CostTotal struct {
	Kind           CostKind
	Currency       string
	Nanos          int64
	Entries        int64
	UnknownEntries int64
	Estimated      bool
}

// StatisticsGroup is one job aggregation group.
type StatisticsGroup struct {
	Key              StatisticsKey
	Jobs             int64
	Completed        int64
	Succeeded        int64
	Failed           int64
	Cancelled        int64
	Skipped          int64
	InfraFailed      int64
	Interrupted      int64
	InProgress       int64
	PricedJobs       int64
	UnpricedJobs     int64
	QueueDuration    DurationSummary
	DispatchDuration DurationSummary
	RunDuration      DurationSummary
	DirectCosts      []CostTotal
}

// FleetCostTotal reports all recorded fleet costs, including direct compute.
// It is grouped independently from workflows so idle/builder costs are never
// misleadingly attributed to a workflow.
type FleetCostTotal struct {
	Tier           string
	Provider       string
	Day            string
	Kind           CostKind
	Currency       string
	Nanos          int64
	Entries        int64
	UnknownEntries int64
	Estimated      bool
}

// FleetTimingTotal reports completed resource phases and open phases accrued at
// read time without attributing boot, idle, reset, or removal overhead to an
// individual workflow. Open phase rows are not mutated by reporting.
type FleetTimingTotal struct {
	Tier     string
	Provider string
	Day      string
	Kind     PhaseKind
	Duration DurationSummary
}

// Statistics is the complete aggregation result.
type Statistics struct {
	Groups       []StatisticsGroup
	FleetCosts   []FleetCostTotal
	FleetTimings []FleetTimingTotal
	Routing      []RoutingEffectiveness
}

// RetentionResult reports rows removed by one retention pass.
type RetentionResult struct {
	Jobs        int64
	Resources   int64
	Generations int64
	Phases      int64
	Snapshots   int64
	Mutations   int64
	Costs       int64
	PriceQuotes int64
}
